version: "3.9"

services:
  yolov5:
    build: .
    container_name: yolov5_container
    volumes:
      - /home/${USER}/workspace:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]